//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetrivingDataFromNW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Cities
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string CountryId { get; set; }
    
        public virtual Test_Countries Test_Countries { get; set; }
    }
}
